# Generated by Django 3.2.9 on 2021-12-11 10:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailadress', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=100)),
            ],
            managers=[
                ('dbTableForEmail', django.db.models.manager.Manager()),
            ],
        ),
    ]
